name: CLI
version: 0.14.11
description: CLI for The Programming Language
license: MIT
main: src/main

packages:
  the/args: 0.3.0
  the/parser: 0.4.16
  the/testing: 0.4.0
  the/yaml: 0.3.0
  the/zip: 0.2.4
