name: CLI
version: 0.14.15
description: CLI for The programming language
license: MIT
main: src/main

packages:
  the/args: 0.3.1
  the/parser: 0.5.0
  the/testing: 0.4.0
  the/yaml: 0.3.0
  the/zip: 0.2.4
