name: CLI
description: CLI for The Programming Language
version: 0.12.1
main: src/main

packages:
  the/args: 0.1.1
  the/error: 1.1.0

scripts:
  build: the build src
  test: the test --exclude src/main
