name: CLI
description: CLI for The Programming Language
version: 0.12.1
main: src/main

packages:
  - the/args: 0.1.0
  - the/error: 1.0.0
  - the/parser: 0.1.0
  - the/testing: 0.1.0

scripts:
  - build: the build src
  - test: the test !src/main
