name: Deploy Packages

on: [workflow_dispatch]

jobs:
  deploy-packages:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential clang cmake libssl-dev libxml2-dev llvm-dev lzma-dev mingw-w64
      - run: mkdir $PWD/the
      - run: |
          git clone https://github.com/tpoechtrager/osxcross.git $PWD/the/osxcross-src
          (cd $PWD/the/osxcross-src && git reset --hard 50e86ebca7d14372febd0af8cd098705049161b9)
          curl -fsSL https://cdn.thelang.io/MacOSX12.3.sdk.tar.xz -o $PWD/the/osxcross-src/tarballs/MacOSX12.3.sdk.tar.xz
          TARGET_DIR=$PWD/the/osxcross UNATTENDED=1 $PWD/the/osxcross-src/build.sh
          rm -rf $PWD/the/osxcross-src
      - run: echo "$PWD/the/osxcross/bin" >> $GITHUB_PATH
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git $PWD/the/linux/openssl-src
          (cd $PWD/the/linux/openssl-src && ./Configure --prefix=$PWD/the/linux no-shared no-tests)
          make -C $PWD/the/linux/openssl-src -j4
          make install_sw -C $PWD/the/linux/openssl-src
          mv $PWD/the/linux/lib64 $PWD/the/linux/lib
          rm -rf $PWD/the/linux/openssl-src
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git $PWD/the/macos/openssl-src
          (cd $PWD/the/macos/openssl-src && CC=clang ./Configure darwin64-x86_64 --cross-compile-prefix=x86_64-apple-darwin21.4- --prefix=$PWD/the/macos no-shared no-tests)
          make -C $PWD/the/macos/openssl-src -j4
          make install_sw -C $PWD/the/macos/openssl-src
          rm -rf $PWD/the/macos/openssl-src
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git $PWD/the/windows/openssl-src
          (cd $PWD/the/windows/openssl-src && ./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32- --prefix=$PWD/the/windows no-shared no-tests)
          make -C $PWD/the/windows/openssl-src -j4
          make install_sw -C $PWD/the/windows/openssl-src
          mv $PWD/the/windows/lib64 $PWD/the/windows/lib
          rm -rf $PWD/the/windows/openssl-src
      - run: tar -czf packages.tar.gz the
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 cp packages.tar.gz s3://${{ secrets.AWS_S3_BUCKET }}/packages.tar.gz --content-type application/x-gzip --content-disposition "attachment; filename=packages.tar.gz"
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/packages.tar.gz"
