on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_CLOUDFRONT_DISTRO: ${{ secrets.AWS_CLOUDFRONT_DISTRO }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws s3 cp configure.sh s3://$AWS_S3_BUCKET/cli@latest \
            --acl public-read \
            --content-type application/octet-stream &&
            aws s3 cp the.sh s3://$AWS_S3_BUCKET/the@latest \
              --acl public-read \
              --content-type application/octet-stream &&
            aws cloudfront create-invalidation \
              --distribution-id $AWS_CLOUDFRONT_DISTRO \
              --paths "/cli@latest" "/the@latest"
