name: Deploy Packages

on: [workflow_dispatch]

jobs:
  deploy-packages:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential clang cmake libssl-dev libxml2-dev llvm-dev lzma-dev mingw-w64
      - run: echo "THE_DIR=$(pwd)/the" >> $GITHUB_ENV
      - run: mkdir $THE_DIR
      - run: |
          git clone https://github.com/tpoechtrager/osxcross.git $THE_DIR/osxcross-src
          (cd $THE_DIR/osxcross-src && git reset --hard 50e86ebca7d14372febd0af8cd098705049161b9)
          curl -fsSL https://cdn.thelang.io/MacOSX12.3.sdk.tar.xz -o $THE_DIR/osxcross-src/tarballs/MacOSX12.3.sdk.tar.xz
          TARGET_DIR=$THE_DIR/osxcross UNATTENDED=1 $THE_DIR/osxcross-src/build.sh
          rm -rf $THE_DIR/osxcross-src
      - run: echo "$THE_DIR/osxcross/bin" >> $GITHUB_PATH
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git $THE_DIR/linux/openssl-src
          (cd $THE_DIR/linux/openssl-src && ./Configure --prefix=$THE_DIR/linux no-shared no-tests)
          make -C $THE_DIR/linux/openssl-src -j4
          make install_sw -C $THE_DIR/linux/openssl-src
          mv $THE_DIR/linux/lib64 $THE_DIR/linux/lib
          rm -rf $THE_DIR/linux/openssl-src
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git $THE_DIR/macos/openssl-src
          (cd $THE_DIR/macos/openssl-src && CC=clang ./Configure darwin64-x86_64 --cross-compile-prefix=x86_64-apple-darwin21.4- --prefix=$THE_DIR/macos no-shared no-tests)
          make -C $THE_DIR/macos/openssl-src -j4
          make install_sw -C $THE_DIR/macos/openssl-src
          rm -rf $THE_DIR/macos/openssl-src
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git $THE_DIR/windows/openssl-src
          (cd $THE_DIR/windows/openssl-src && ./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32- --prefix=$THE_DIR/windows no-shared no-tests)
          make -C $THE_DIR/windows/openssl-src -j4
          make install_sw -C $THE_DIR/windows/openssl-src
          mv $THE_DIR/windows/lib64 $THE_DIR/windows/lib
          rm -rf $THE_DIR/windows/openssl-src
      - run: tar -czf packages.tgz the
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 cp packages.tgz s3://${{ secrets.AWS_S3_BUCKET }}/packages.tgz --content-type application/gzip
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/packages.tgz"
