name: Deploy Packages

on: [workflow_dispatch]

jobs:
  deploy-packages:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential clang cmake libssl-dev libxml2-dev llvm-dev lzma-dev mingw-w64
      - run: |
          git clone https://github.com/tpoechtrager/osxcross.git /usr/local/the/osxcross-src
          (cd /usr/local/the/osxcross-src && git reset --hard 50e86ebca7d14372febd0af8cd098705049161b9)
          curl -fsSL https://cdn.thelang.io/MacOSX12.3.sdk.tar.xz -o /usr/local/the/osxcross-src/tarballs/MacOSX12.3.sdk.tar.xz
          TARGET_DIR=/usr/local/the/osxcross UNATTENDED=1 /usr/local/the/osxcross-src/build.sh
          rm -rf /usr/local/the/osxcross-src
      - run: echo "/usr/local/the/osxcross/bin" >> $GITHUB_PATH
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git /usr/local/the/linux/openssl-src
          (cd /usr/local/the/linux/openssl-src && ./Configure --prefix=/usr/local/the/linux no-shared no-tests)
          make -C /usr/local/the/linux/openssl-src -j4
          make install_sw -C /usr/local/the/linux/openssl-src
          mv /usr/local/the/linux/lib64 /usr/local/the/linux/lib
          rm -rf /usr/local/the/linux/openssl-src
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git /usr/local/the/macos/openssl-src
          (cd /usr/local/the/macos/openssl-src && CC=clang ./Configure darwin64-x86_64 --cross-compile-prefix=x86_64-apple-darwin21.4- --prefix=/usr/local/the/macos no-shared no-tests)
          make -C /usr/local/the/macos/openssl-src -j4
          make install_sw -C /usr/local/the/macos/openssl-src
          rm -rf /usr/local/the/macos/openssl-src
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git /usr/local/the/windows/openssl-src
          (cd /usr/local/the/windows/openssl-src && ./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32- --prefix=/usr/local/the/windows no-shared no-tests)
          make -C /usr/local/the/windows/openssl-src -j4
          make install_sw -C /usr/local/the/windows/openssl-src
          mv /usr/local/the/windows/lib64 /usr/local/the/windows/lib
          rm -rf /usr/local/the/windows/openssl-src
      - run: (cd /usr/local && tar -czf packages.tgz the)
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 cp packages.tgz s3://${{ secrets.AWS_S3_BUCKET }}/packages.tgz --content-type application/gzip
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/packages.tgz"
