name: Deploy Packages

on: [workflow_dispatch]

jobs:
  deploy-packages:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential clang cmake libssl-dev libxml2-dev llvm-dev lzma-dev mingw-w64
      - run: echo "INSTALL_DIR=$PWD/the/osxcross" >> $GITHUB_ENV
      - run: |
          git clone https://github.com/tpoechtrager/osxcross.git $INSTALL_DIR/osxcross-src
          (cd $INSTALL_DIR/osxcross-src && git reset --hard 50e86ebca7d14372febd0af8cd098705049161b9)
          curl -fsSL https://cdn.thelang.io/MacOSX12.3.sdk.tar.xz -o $INSTALL_DIR/osxcross-src/tarballs/MacOSX12.3.sdk.tar.xz
          TARGET_DIR=$INSTALL_DIR UNATTENDED=1 $INSTALL_DIR/osxcross-src/build.sh
          rm -rf $INSTALL_DIR/osxcross-src
      - run: echo "$INSTALL_DIR/bin" >> $GITHUB_PATH
      - run: echo "OPENSSL_ARGS=no-engine no-module no-shared no-stdio no-tests no-threads --libdir=lib" >> $GITHUB_ENV
      - run: echo "INSTALL_DIR=$PWD/the/linux" >> $GITHUB_ENV
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git $INSTALL_DIR/openssl-src
          (cd $INSTALL_DIR/openssl-src && CC=clang ./Configure $OPENSSL_ARGS --openssldir=/usr/local/ssl-linux --prefix=$INSTALL_DIR)
          make -C $INSTALL_DIR/openssl-src -j4
          make install_sw -C $INSTALL_DIR/openssl-src
          rm -rf $INSTALL_DIR/openssl-src
      - run: echo "INSTALL_DIR=$PWD/the/macos" >> $GITHUB_ENV
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git $INSTALL_DIR/openssl-src
          (cd $INSTALL_DIR/openssl-src && CC=clang ./Configure darwin64-x86_64 $OPENSSL_ARGS --cross-compile-prefix=x86_64-apple-darwin21.4- --openssldir=/usr/local/ssl-macos --prefix=$INSTALL_DIR)
          make -C $INSTALL_DIR/openssl-src -j4
          make install_sw -C $INSTALL_DIR/openssl-src
          rm -rf $INSTALL_DIR/openssl-src
      - run: echo "INSTALL_DIR=$PWD/the/windows" >> $GITHUB_ENV
      - run: |
          git clone --depth 1 --branch openssl-3.0.7 https://github.com/openssl/openssl.git $INSTALL_DIR/openssl-src
          (cd $INSTALL_DIR/openssl-src && ./Configure mingw64 $OPENSSL_ARGS --cross-compile-prefix=x86_64-w64-mingw32- --openssldir=/usr/local/ssl-windows --prefix=$INSTALL_DIR)
          make -C $INSTALL_DIR/openssl-src -j4
          make install_sw -C $INSTALL_DIR/openssl-src
          rm -rf $INSTALL_DIR/openssl-src
      - run: tar -czf packages.tar.gz the
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 cp packages.tar.gz s3://${{ secrets.AWS_S3_BUCKET }}/packages.tar.gz --content-type application/x-gzip --content-disposition "attachment; filename=packages.tar.gz"
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/packages.tar.gz"
