on:
  push:
    branches: [main]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_S3_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
  AWS_CLOUDFRONT_DISTRO: ${{ secrets.AWS_CLOUDFRONT_DISTRO }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          aws s3 cp configure.sh s3://$AWS_S3_BUCKET/cli@latest \
            --acl public-read \
            --content-type application/octet-stream
      - run: |
          aws s3 cp the.sh s3://$AWS_S3_BUCKET/the@latest \
            --acl public-read \
            --content-type application/octet-stream
      - run: |
          aws cloudfront create-invalidation \
            --distribution-id $AWS_CLOUDFRONT_DISTRO \
            --paths "/cli@latest" "/the@latest"
