name: Test

on:
  push:
    branches: [main]
    paths-ignore: ['**/*.md', '**/*.yml', '!.github/workflows/test.yml']
  pull_request:
    paths-ignore: ['**/*.md', '**/*.yml', '!.github/workflows/test.yml']

concurrency:
  cancel-in-progress: true
  group: test-${{ github.event.pull_request.number || github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: thelang-io/setup-the@v1
      - run: sudo apt-get update
      - run: sudo apt-get install valgrind
      - run: the install
      - run: ./build.out compile src/main && mv a.out b.out
      - run: valgrind ./b.out -h
      - run: valgrind ./b.out -v
