name: Test

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - "**.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.yml"

concurrency:
  cancel-in-progress: true
  group: test-${{ github.event.pull_request.number || github.sha }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install valgrind
      - run: curl -fsSL https://cdn.thelang.io/cli | sh
      - run: ./build.sh
      - run: the compile build/result && mv a.out b.out
      - run: valgrind b.out -h
      - run: valgrind b.out -v
      - run: valgrind b.out build
      - run: valgrind b.out lex build/result
      - run: valgrind b.out parse build/result
      - run: valgrind b.out compile build/result
      - run: valgrind b.out run build/result
